/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as RegisterRouteImport } from './app/routes/register'
import { Route as LoginRouteImport } from './app/routes/login'
import { Route as AuthenticatedRouteImport } from './app/routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './app/routes/_authenticated/index'
import { Route as InvitationsAcceptRouteImport } from './app/routes/invitations/accept'
import { Route as AuthenticatedOrgsOrgSlugRouteImport } from './app/routes/_authenticated/orgs/$orgSlug'
import { Route as AuthenticatedOrgsOrgSlugIndexRouteImport } from './app/routes/_authenticated/orgs/$orgSlug/index'
import { Route as AuthenticatedOrgsOrgSlugSettingsRouteImport } from './app/routes/_authenticated/orgs/$orgSlug/settings'
import { Route as AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRouteImport } from './app/routes/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug'
import { Route as AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugIndexRouteImport } from './app/routes/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/index'
import { Route as AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugMembersRouteImport } from './app/routes/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/members'
import { Route as AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugInvoicesRouteImport } from './app/routes/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/invoices'
import { Route as AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugInboxRouteImport } from './app/routes/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/inbox'
import { Route as AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugSuppliersIndexRouteImport } from './app/routes/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/suppliers/index'
import { Route as AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugSuppliersSupplierIdRouteImport } from './app/routes/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/suppliers/$supplierId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrgsOrgSlugRoute =
  AuthenticatedOrgsOrgSlugRouteImport.update({
    id: '/orgs/$orgSlug',
    path: '/orgs/$orgSlug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgsOrgSlugIndexRoute =
  AuthenticatedOrgsOrgSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgsOrgSlugRoute,
  } as any)
const AuthenticatedOrgsOrgSlugSettingsRoute =
  AuthenticatedOrgsOrgSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOrgsOrgSlugRoute,
  } as any)
const AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRoute =
  AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRouteImport.update({
    id: '/workspaces/$workspaceSlug',
    path: '/workspaces/$workspaceSlug',
    getParentRoute: () => AuthenticatedOrgsOrgSlugRoute,
  } as any)
const AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugIndexRoute =
  AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRoute,
  } as any)
const AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugMembersRoute =
  AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRoute,
  } as any)
const AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugInvoicesRoute =
  AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRoute,
  } as any)
const AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugInboxRoute =
  AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugInboxRouteImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRoute,
  } as any)
const AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugSuppliersIndexRoute =
  AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugSuppliersIndexRouteImport.update(
    {
      id: '/suppliers/',
      path: '/suppliers/',
      getParentRoute: () =>
        AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRoute,
    } as any,
  )
const AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugSuppliersSupplierIdRoute =
  AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugSuppliersSupplierIdRouteImport.update(
    {
      id: '/suppliers/$supplierId',
      path: '/suppliers/$supplierId',
      getParentRoute: () =>
        AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/orgs/$orgSlug': typeof AuthenticatedOrgsOrgSlugRouteWithChildren
  '/orgs/$orgSlug/settings': typeof AuthenticatedOrgsOrgSlugSettingsRoute
  '/orgs/$orgSlug/': typeof AuthenticatedOrgsOrgSlugIndexRoute
  '/orgs/$orgSlug/workspaces/$workspaceSlug': typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRouteWithChildren
  '/orgs/$orgSlug/workspaces/$workspaceSlug/inbox': typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugInboxRoute
  '/orgs/$orgSlug/workspaces/$workspaceSlug/invoices': typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugInvoicesRoute
  '/orgs/$orgSlug/workspaces/$workspaceSlug/members': typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugMembersRoute
  '/orgs/$orgSlug/workspaces/$workspaceSlug/': typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugIndexRoute
  '/orgs/$orgSlug/workspaces/$workspaceSlug/suppliers/$supplierId': typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugSuppliersSupplierIdRoute
  '/orgs/$orgSlug/workspaces/$workspaceSlug/suppliers/': typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugSuppliersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/': typeof AuthenticatedIndexRoute
  '/orgs/$orgSlug/settings': typeof AuthenticatedOrgsOrgSlugSettingsRoute
  '/orgs/$orgSlug': typeof AuthenticatedOrgsOrgSlugIndexRoute
  '/orgs/$orgSlug/workspaces/$workspaceSlug/inbox': typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugInboxRoute
  '/orgs/$orgSlug/workspaces/$workspaceSlug/invoices': typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugInvoicesRoute
  '/orgs/$orgSlug/workspaces/$workspaceSlug/members': typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugMembersRoute
  '/orgs/$orgSlug/workspaces/$workspaceSlug': typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugIndexRoute
  '/orgs/$orgSlug/workspaces/$workspaceSlug/suppliers/$supplierId': typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugSuppliersSupplierIdRoute
  '/orgs/$orgSlug/workspaces/$workspaceSlug/suppliers': typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugSuppliersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/orgs/$orgSlug': typeof AuthenticatedOrgsOrgSlugRouteWithChildren
  '/_authenticated/orgs/$orgSlug/settings': typeof AuthenticatedOrgsOrgSlugSettingsRoute
  '/_authenticated/orgs/$orgSlug/': typeof AuthenticatedOrgsOrgSlugIndexRoute
  '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug': typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRouteWithChildren
  '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/inbox': typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugInboxRoute
  '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/invoices': typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugInvoicesRoute
  '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/members': typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugMembersRoute
  '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/': typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugIndexRoute
  '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/suppliers/$supplierId': typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugSuppliersSupplierIdRoute
  '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/suppliers/': typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugSuppliersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/invitations/accept'
    | '/orgs/$orgSlug'
    | '/orgs/$orgSlug/settings'
    | '/orgs/$orgSlug/'
    | '/orgs/$orgSlug/workspaces/$workspaceSlug'
    | '/orgs/$orgSlug/workspaces/$workspaceSlug/inbox'
    | '/orgs/$orgSlug/workspaces/$workspaceSlug/invoices'
    | '/orgs/$orgSlug/workspaces/$workspaceSlug/members'
    | '/orgs/$orgSlug/workspaces/$workspaceSlug/'
    | '/orgs/$orgSlug/workspaces/$workspaceSlug/suppliers/$supplierId'
    | '/orgs/$orgSlug/workspaces/$workspaceSlug/suppliers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/invitations/accept'
    | '/'
    | '/orgs/$orgSlug/settings'
    | '/orgs/$orgSlug'
    | '/orgs/$orgSlug/workspaces/$workspaceSlug/inbox'
    | '/orgs/$orgSlug/workspaces/$workspaceSlug/invoices'
    | '/orgs/$orgSlug/workspaces/$workspaceSlug/members'
    | '/orgs/$orgSlug/workspaces/$workspaceSlug'
    | '/orgs/$orgSlug/workspaces/$workspaceSlug/suppliers/$supplierId'
    | '/orgs/$orgSlug/workspaces/$workspaceSlug/suppliers'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/invitations/accept'
    | '/_authenticated/'
    | '/_authenticated/orgs/$orgSlug'
    | '/_authenticated/orgs/$orgSlug/settings'
    | '/_authenticated/orgs/$orgSlug/'
    | '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug'
    | '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/inbox'
    | '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/invoices'
    | '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/members'
    | '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/'
    | '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/suppliers/$supplierId'
    | '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/suppliers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orgs/$orgSlug': {
      id: '/_authenticated/orgs/$orgSlug'
      path: '/orgs/$orgSlug'
      fullPath: '/orgs/$orgSlug'
      preLoaderRoute: typeof AuthenticatedOrgsOrgSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$orgSlug/': {
      id: '/_authenticated/orgs/$orgSlug/'
      path: '/'
      fullPath: '/orgs/$orgSlug/'
      preLoaderRoute: typeof AuthenticatedOrgsOrgSlugIndexRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgSlugRoute
    }
    '/_authenticated/orgs/$orgSlug/settings': {
      id: '/_authenticated/orgs/$orgSlug/settings'
      path: '/settings'
      fullPath: '/orgs/$orgSlug/settings'
      preLoaderRoute: typeof AuthenticatedOrgsOrgSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgSlugRoute
    }
    '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug': {
      id: '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug'
      path: '/workspaces/$workspaceSlug'
      fullPath: '/orgs/$orgSlug/workspaces/$workspaceSlug'
      preLoaderRoute: typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgSlugRoute
    }
    '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/': {
      id: '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/'
      path: '/'
      fullPath: '/orgs/$orgSlug/workspaces/$workspaceSlug/'
      preLoaderRoute: typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugIndexRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRoute
    }
    '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/members': {
      id: '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/members'
      path: '/members'
      fullPath: '/orgs/$orgSlug/workspaces/$workspaceSlug/members'
      preLoaderRoute: typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugMembersRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRoute
    }
    '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/invoices': {
      id: '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/invoices'
      path: '/invoices'
      fullPath: '/orgs/$orgSlug/workspaces/$workspaceSlug/invoices'
      preLoaderRoute: typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugInvoicesRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRoute
    }
    '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/inbox': {
      id: '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/inbox'
      path: '/inbox'
      fullPath: '/orgs/$orgSlug/workspaces/$workspaceSlug/inbox'
      preLoaderRoute: typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugInboxRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRoute
    }
    '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/suppliers/': {
      id: '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/suppliers/'
      path: '/suppliers'
      fullPath: '/orgs/$orgSlug/workspaces/$workspaceSlug/suppliers/'
      preLoaderRoute: typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRoute
    }
    '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/suppliers/$supplierId': {
      id: '/_authenticated/orgs/$orgSlug/workspaces/$workspaceSlug/suppliers/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/orgs/$orgSlug/workspaces/$workspaceSlug/suppliers/$supplierId'
      preLoaderRoute: typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugSuppliersSupplierIdRouteImport
      parentRoute: typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRoute
    }
  }
}

interface AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRouteChildren {
  AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugInboxRoute: typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugInboxRoute
  AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugInvoicesRoute: typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugInvoicesRoute
  AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugMembersRoute: typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugMembersRoute
  AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugIndexRoute: typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugIndexRoute
  AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugSuppliersSupplierIdRoute: typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugSuppliersSupplierIdRoute
  AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugSuppliersIndexRoute: typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugSuppliersIndexRoute
}

const AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRouteChildren: AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRouteChildren =
  {
    AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugInboxRoute:
      AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugInboxRoute,
    AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugInvoicesRoute:
      AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugInvoicesRoute,
    AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugMembersRoute:
      AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugMembersRoute,
    AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugIndexRoute:
      AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugIndexRoute,
    AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugSuppliersSupplierIdRoute:
      AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugSuppliersSupplierIdRoute,
    AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugSuppliersIndexRoute:
      AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugSuppliersIndexRoute,
  }

const AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRouteWithChildren =
  AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRoute._addFileChildren(
    AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRouteChildren,
  )

interface AuthenticatedOrgsOrgSlugRouteChildren {
  AuthenticatedOrgsOrgSlugSettingsRoute: typeof AuthenticatedOrgsOrgSlugSettingsRoute
  AuthenticatedOrgsOrgSlugIndexRoute: typeof AuthenticatedOrgsOrgSlugIndexRoute
  AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRoute: typeof AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRouteWithChildren
}

const AuthenticatedOrgsOrgSlugRouteChildren: AuthenticatedOrgsOrgSlugRouteChildren =
  {
    AuthenticatedOrgsOrgSlugSettingsRoute:
      AuthenticatedOrgsOrgSlugSettingsRoute,
    AuthenticatedOrgsOrgSlugIndexRoute: AuthenticatedOrgsOrgSlugIndexRoute,
    AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRoute:
      AuthenticatedOrgsOrgSlugWorkspacesWorkspaceSlugRouteWithChildren,
  }

const AuthenticatedOrgsOrgSlugRouteWithChildren =
  AuthenticatedOrgsOrgSlugRoute._addFileChildren(
    AuthenticatedOrgsOrgSlugRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOrgsOrgSlugRoute: typeof AuthenticatedOrgsOrgSlugRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOrgsOrgSlugRoute: AuthenticatedOrgsOrgSlugRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
